markdown: rdiscount
pygments: true
permalink: none
sitename: JavaScript 标准参考教程（alpha）

chapters:
- introduction
- grammar
- stdlib
- oop
- dom 
- bom
- htmlapi
- jquery
- library
- tool
- special
- nodejs

introduction: 导论
grammar: 基本语法
stdlib: 标准库
oop: 面向对象编程
dom: DOM
bom: 浏览器对象
htmlapi: HTML网页的API
jquery: jQuery
library: 函数库
nodejs: 附录：Node.js
tool: 开发工具
special: 专题
