markdown: rdiscount
pygments: true
permalink: none
sitename: Javascript 标准教程

chapters:
- dom 
- htmlapi
- algorithm
- jquery
- tool

dom: DOM
htmlapi: HTML5 API
algorithm: 算法（Algorithm）
jquery: jQuery
tool: 开发工具
